spring:
    cache:
      jcache:
        config: classpath:ehcache.xml

    http:
        encoding:
          charset: UTF-8
          force: true
          enabled: true

    datasource:
        dbdongann:
          url: '@dbdongann.url@'
          username: '@dbdongann.username@'
          password: '@dbdongann.password@'
          type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20

logging:
    level:
      com.dongann: DEBUG
      console: DEBUG
      org.mybatis.example: DEBUG

server:
  port: 8088
